# Generated by Django 5.2.4 on 2025-08-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0001_initial"),
        ("users", "0007_rename_bloodbank_staffprofile_bloodbank_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="camp",
            name="organizer_content_type",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="organizer_object_id",
        ),
        migrations.RemoveField(
            model_name="camp",
            name="partner_bloodbank",
        ),
        migrations.AddField(
            model_name="camp",
            name="bloodbank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="camps",
                to="users.bloodbankprofile",
            ),
        ),
        migrations.AddField(
            model_name="camp",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="camps",
                to="users.organizationprofile",
            ),
        ),
        migrations.AlterField(
            model_name="camp",
            name="address",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="camp",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="camp",
            name="end_time",
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name="camp",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="camp",
            name="start_time",
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name="CampSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("capacity", models.PositiveIntegerField(default=10)),
                ("booked_count", models.PositiveIntegerField(default=0)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="camp.camp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CampAppointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("BOOKED", "Booked"),
                            ("ATTENDED", "Attended"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="BOOKED",
                        max_length=10,
                    ),
                ),
                ("booked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="camp.camp",
                    ),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="camp_appointments",
                        to="users.donorprofile",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="camp.campslot",
                    ),
                ),
            ],
            options={
                "unique_together": {("slot", "donor")},
            },
        ),
        migrations.DeleteModel(
            name="CampRegistration",
        ),
    ]
