# Generated by Django 5.2.4 on 2025-08-20 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0002_remove_camp_organizer_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
