# Generated by Django 5.2.4 on 2025-08-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0003_alter_camp_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="camp",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "upcoming"),
                    ("CURRENT", "Current"),
                    ("DONE", "done"),
                ],
                default="UPCOMING",
                max_length=10,
            ),
        ),
    ]
