# Generated by Django 5.2.4 on 2025-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0004_camp_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="camp",
            name="status",
            field=models.CharField(
                choices=[
                    ("UPCOMING", "Upcoming"),
                    ("CURRENT", "Current"),
                    ("DONE", "Done"),
                ],
                default="UPCOMING",
                max_length=10,
            ),
        ),
    ]
