# Generated by Django 5.2.4 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0005_alter_camp_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campappointment",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("VISITED", "Visited"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="BOOKED",
                max_length=10,
            ),
        ),
    ]
