# Generated by Django 5.2.4 on 2025-08-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodbankprofile",
            name="email",
        ),
    ]
