# Generated by Django 5.2.4 on 2025-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_organizationprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="dob",
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name="donorprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
