# Generated by Django 5.2.4 on 2025-08-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_donorprofile_dob_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile_pic.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="patientprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile_pic.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                default="profile_pics/profile_pic.jpg",
                null=True,
                upload_to="profile_pics/",
            ),
        ),
    ]
