# Generated by Django 5.2.4 on 2025-08-18 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_donorprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodbankprofile",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="organizationprofile",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="staffprofile",
            name="approved",
        ),
        migrations.AddField(
            model_name="bloodbankprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="staffprofile",
            name="approval_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Denied", "Denied"),
                ],
                default="Pending",
                max_length=20,
            ),
        ),
    ]
