# Generated by Django 5.2.4 on 2025-08-19 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_bloodbankprofile_approved_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="staffprofile",
            old_name="bloodbank",
            new_name="bloodbank_name",
        ),
    ]
