# Generated by Django 5.2.4 on 2025-08-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_rename_bloodbank_staffprofile_bloodbank_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donorprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
