# Generated by Django 5.2.4 on 2025-08-31 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_adminprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodbankprofile",
            name="authorize_number",
            field=models.IntegerField(unique=True),
        ),
    ]
