# Generated by Django 5.2.4 on 2025-09-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_bloodbankprofile_authorize_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patientprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
        migrations.AlterField(
            model_name="staffprofile",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
