# Generated by Django 5.2.4 on 2025-08-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0003_alter_bloodrequest_blood_group"),
        ("users", "0009_alter_adminprofile_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralBloodRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patient_name", models.CharField(max_length=100)),
                ("blood_group", models.CharField(max_length=10)),
                ("location", models.CharField(max_length=200)),
                ("date_requested", models.DateTimeField(auto_now_add=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="donations",
                        to="users.donorprofile",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="requests",
                        to="users.patientprofile",
                    ),
                ),
            ],
        ),
    ]
