# Generated by Django 5.2.4 on 2025-08-29 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0004_generalbloodrequest"),
        ("users", "0009_alter_adminprofile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generalbloodrequest",
            name="donor_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="generalbloodrequest",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.donorprofile",
            ),
        ),
        migrations.AlterField(
            model_name="generalbloodrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.patientprofile"
            ),
        ),
    ]
