# Generated by Django 5.2.4 on 2025-08-29 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0005_generalbloodrequest_donor_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="generalbloodrequest",
            name="donor_name",
        ),
    ]
