# Generated by Django 5.2.4 on 2025-09-06 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0007_alter_generalbloodrequest_blood_group"),
        ("users", "0011_alter_patientprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="bloodrequest",
            name="accepted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accepted_requests",
                to="users.staffprofile",
            ),
        ),
    ]
