# Generated by Django 5.2.4 on 2025-09-06 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("patients", "0008_bloodrequest_accepted_by"),
        ("users", "0011_alter_patientprofile_profile_pic_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bloodrequest",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="users.patientprofile",
            ),
        ),
    ]
