# Generated by Django 5.2.4 on 2025-08-19 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0002_remove_camp_organizer_content_type_and_more"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bloodinventory",
            old_name="units_available",
            new_name="units_aviable",
        ),
        migrations.AlterField(
            model_name="bloodinventory",
            name="blood_group",
            field=models.CharField(
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                ],
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="CampInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                        ],
                        max_length=3,
                    ),
                ),
                ("units_collected", models.PositiveIntegerField(default=0)),
                (
                    "camp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventory",
                        to="camp.camp",
                    ),
                ),
            ],
        ),
    ]
