# Generated by Django 5.2.4 on 2025-08-22 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("camp", "0004_camp_status"),
        (
            "inventory",
            "0002_rename_units_available_bloodinventory_units_aviable_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="campinventory",
            unique_together={("camp", "blood_group")},
        ),
    ]
