# Generated by Django 5.2.4 on 2025-08-22 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_campinventory_unique_together"),
        ("users", "0009_alter_adminprofile_first_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="BloodInventory",
            new_name="BloodBankInventory",
        ),
        migrations.RenameField(
            model_name="bloodbankinventory",
            old_name="units_aviable",
            new_name="units_available",
        ),
    ]
