# Generated by Django 5.2.4 on 2025-08-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("DONOR", "Donor"),
                    ("PATIENT", "Patient"),
                    ("BLOODBANK", "Blood Bank"),
                    ("ORG", "org"),
                    ("STAFF", "Staff"),
                    ("ADMIN", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
